# Generated by Django 6.0.6 on 2026-06-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.CharField(choices=[('alimentation', 'Alimentation'), ('vetements', 'Vêtements'), ('electronique', 'Électronique'), ('beaute', 'Beauté'), ('maison', 'Maison'), ('sport', 'Sport'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='boutiques.boutique')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
